### ISSUE TITLE
Problem with spread operator

### ISSUE THREAD

**Issue by knobo** [ternjs/tern#1003]
Version: 0.23.0
This fails: `condense test.jsx`

``` 
export function test({  ...detailProps }) {
  return (
  );
}
```
output:
```
/home/knobo/.config/yarn/global/node_modules/tern/lib/infer.js:1072
    if (node.type == "Identifier") return node.name;
             ^

TypeError: Cannot read property 'type' of undefined
    at patternName (/home/knobo/.config/yarn/global/node_modules/tern/lib/infer.js:1072:14)
    at /home/knobo/.config/yarn/global/node_modules/tern/lib/infer.js:1074:93
    at Array.map (<anonymous>)
    at patternName (/home/knobo/.config/yarn/global/node_modules/tern/lib/infer.js:1074:68)
    at Object.Function (/home/knobo/.config/yarn/global/node_modules/tern/lib/infer.js:1113:23)
    at c (/home/knobo/.config/yarn/global/node_modules/acorn-walk/dist/walk.js:57:35)
    at Object.base.FunctionDeclaration (/home/knobo/.config/yarn/global/node_modules/acorn-walk/dist/walk.js:271:60)
    at c (/home/knobo/.config/yarn/global/node_modules/acorn-walk/dist/walk.js:57:35)
    at Object.skipThrough (/home/knobo/.config/yarn/global/node_modules/acorn-walk/dist/walk.js:183:37)
    at c (/home/knobo/.config/yarn/global/node_modules/acorn-walk/dist/walk.js:57:35)
```

**Comment by othree** [comment]
The parser upgraded since 0.22.
So this syntax is just skipped in the past.

Thanks for reporting.
