### ISSUE TITLE
Failed to launch development process with webpack after installing tern@latest npm package

### ISSUE THREAD

**Issue by liuliangsir** [ternjs/tern#1041]
Here are a bunch of logs.

<details>
  <summary>Details</summary>
ModuleDependencyError: Can't import the named export 'tokTypes' from non EcmaScript module (only default export is available)
    at Compilation.reportDependencyErrorsAndWarnings (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1468:21)
    at hooks.finishModules.callAsync.err (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1258:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\work\netease\avg-editor-web\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (D:\work\netease\avg-editor-web\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1253:28)
    at hooks.make.callAsync.err (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compiler.js:672:17)
    at _err0 (eval at create (D:\work\netease\avg-editor-web\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1185:12)
    at processModuleDependencies.err (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1097:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
    at HarmonyImportSpecifierDependency._getErrors (D:\work\netease\avg-editor-web\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (D:\work\netease\avg-editor-web\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1463:22)
    at hooks.finishModules.callAsync.err (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1258:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\work\netease\avg-editor-web\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (D:\work\netease\avg-editor-web\node_modules\tapable\lib\Hook.js:154:20)
    at Compilation.finish (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1253:28)
    at hooks.make.callAsync.err (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compiler.js:672:17)
    at _err0 (eval at create (D:\work\netease\avg-editor-web\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at _addModuleChain (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1185:12)
    at processModuleDependencies.err (D:\work\netease\avg-editor-web\node_modules\webpack\lib\Compilation.js:1097:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
</details>

**Comment by othree** [comment]
This is very unclear. I don't know what you want to do. Please provide your project or create a smallest reproducible repo.

**Comment by liuliangsir** [comment]
@othree okay, I will create a a smallest reproducible repo
