### ISSUE TITLE
Node plugin fails with "Cannot call method 'propagate' on undefined" when `var module = ...` is encountered

### ISSUE THREAD

**Issue by sqs** [ternjs/tern#137]
Running the node plugin on JS code that contains `var module = ...` throws an error:

```
$ echo 'var module = {};' | bin/condense --plugin node /dev/stdin

/home/sqs/src/tern/plugin/node.js:134
      exportsFromScope(file.scope).propagate(getModule(this._node, file.name))
                                   ^
TypeError: Cannot call method 'propagate' of undefined
    at Object.<anonymous> (/home/sqs/src/tern/plugin/node.js:134:36)
    at Object.Server.signal (/home/sqs/src/tern/lib/tern.js:152:60)
    at /home/sqs/src/tern/lib/tern.js:216:11
    at Object.exports.withContext (/home/sqs/src/tern/lib/infer.js:596:18)
    at analyzeFile (/home/sqs/src/tern/lib/tern.js:210:11)
    at analyzeAll (/home/sqs/src/tern/lib/tern.js:296:36)
    at Object.Server.flush (/home/sqs/src/tern/lib/tern.js:136:7)
    at Object.<anonymous> (/home/sqs/src/tern/bin/condense:89:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

This is because the type of `scope.getProp("module")` is the union of node.js `module` and `{}`:

``` javascript
{ types: 
   [ { props: [Object],
       proto: [Object],
       name: 'Module',
       maybeProps: null,
       origin: null },
     { props: {},
       proto: [Object],
       name: 'module',
       maybeProps: null,
       origin: '/dev/stdin',
       originNode: [Object] } ],
  forward: null,
  maxWeight: 100,
  originNode: { type: 'Identifier', start: 4, end: 10, name: 'module' },
  origin: null }
```

as opposed to what it would be without a `var module = ...`:

``` javascript
{ types: 
   [ { props: [Object],
       proto: [Object],
       name: 'Module',
       maybeProps: null,
       origin: null } ],
  forward: null,
  maxWeight: 100,
  originNode: undefined,
  origin: null }
```

Context/motivation: using `var module = ...` is part of a somewhat common technique for abstracting away browser/node.js module export behaviors (~5% of npm packages in my npm cache use this technique). One example of it in the wild is at https://github.com/Marak/colors.js/blob/master/colors.js#L37.

The fix for this could be tough. I would be in favor of just ignoring reassignments to `module` when the node.js plugin is enabled, as I am not aware of any valid reasons for redeclaring `module` in node.js code.

**Comment by buteomont** [comment]
I know this is an old problem, but I'm having the same problem.  Here's the console trace:
.tern-project: {"ide":{},"libs":["ecma5","browser"],"plugins":{"node":{},"meteor":{}}}
Project dir: /home/david/workspaces/javascript/SolutionExplorer
Nodejs Commnand: "/usr/local/bin/node" "/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/bin/tern" --no-port-file
Server started at 39885 in 414ms
-----------------------------------
Tern request#: 
{"files":[{"name":"solutionExplorer.html","text":"","type":"full"}]}

Tern response# with 309ms: 
{}
-----------------------------------
/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/plugin/node.js:191
      exportsFromScope(file.scope).exports.propagate(mod);
                                          ^
TypeError: Cannot read property 'propagate' of undefined
    at Object.<anonymous> (/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/plugin/node.js:191:43)
    at Object.signal (/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/signal.js:19:58)
    at /home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/tern.js:228:11
    at Object.exports.withContext (/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/infer.js:759:18)
    at doRequest (/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/tern.js:193:7)
    at respond (/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/bin/tern:224:10)
    at IncomingMessage.<anonymous> (/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/bin/tern:190:32)
    at analyzeAll (/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/tern.js:329:11)
    at Object.signal.mixin.request (/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/tern.js:143:7)
    at analyzeFile (/home/david/.eclipse/org.eclipse.platform_4.4.2_371948527_linux_gtk_x86_64/plugins/ternjs_0.10.0.201506172156/node_modules/tern/lib/tern.js:224:11)


How can I fix it?

**Comment by angelozerr** [comment]
@buteomont I have tested and I have the same problem than you. It seems that it's because use of node + meteor together. If you remove meteor tern plugin, the error disappears. 

I suggest you that you create issues at https://github.com/Slava/tern-meteor/issues

**Comment by thinklinux** [comment]
@marijnh @angelozerr 

Hi guys. I fixed the problem as I check if file.scope.exports exists:

```
  var exports = file.scope.exports;
  if (exports) {
    exports.propagate(mod);
  }
```
Do you think that's a good solution? If so I can make a pull request. I tried with the dontLoad solution for the node module bug it didn't work for me.

**Comment by marijnh** [comment]
The node plugin, as it exists, will wrap the scope of every file loaded, and attach an `exports` property. If another plugin messes with that scope and replaced it with one that doesn't have `exports`, the two plugins simply don't work together (the node plugin won't be able to function).
