### ISSUE TITLE
[emacs plugin] Could not start Tern server

### ISSUE THREAD

**Issue by exu** [ternjs/tern#233]
Emacs gave me this message, 

```
tern-message: Wrong type argument: listp, "Could not start Tern server

undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at readProjectFile (/home/exu/Dropbox/Dotfiles/common/emacs.d/vendor/tern/bin/tern:45:19)
    at Object.<anonymous> (/home/exu/Dropbox/Dotfiles/common/emacs.d/vendor/tern/bin/tern:100:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

do I need run this server manually?

My config file:

```
(add-to-list 'load-path "~/.emacs.d/vendor/tern/emacs/")
(autoload 'tern-mode "tern.el" nil t)
(add-hook 'js-mode-hook (lambda () (tern-mode t)))
(add-hook 'js3-mode-hook (lambda () (tern-mode t)))
(eval-after-load 'tern
   '(progn
      (require 'tern-auto-complete)
      (tern-ac-setup)))
```

If I run `bin/tern` manually and then `M-x tern-use-server` to port then everyting works fine, but its little annoying.

**Comment by gennarocoppola8** [comment]
I have problems with my config too, I don't know where my .tern-project should be? I think in the root of the project, is it?
