### ISSUE TITLE
TypeError: inferExprVisitor[node.type] is not a function

### ISSUE THREAD

**Issue by yyangonline** [ternjs/tern#671]
Tern is not working for me. And I debug with --verbose, here is what I get.

/usr/local/bin/node /Users/a/.vim/bundle/tern_for_vim/autoload/../node_modules/tern/bin/tern --verbose
Listening on port 64174
Request: {
  "files": [],
  "query": {
    "end": {
      "line": 16,
      "ch": 9
    },
    "lineCharPositions": true,
    "type": "definition",
    "file": "index.ios.js"
  }
}
/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/lib/infer.js:1100
    return inferExprVisitor[node.type](node, scope, c, out, name);
                                      ^

TypeError: inferExprVisitor[node.type] is not a function
    at infer (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/lib/infer.js:1100:39)
    at Object.walk.make.Expression (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/lib/infer.js:1105:7)
    at c (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.base.ExpressionStatement (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:176:5)
    at c (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.skipThrough [as Statement] (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:163:39)
    at c (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.base.Program.base.BlockStatement (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:171:7)
    at c (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.skipThrough [as Statement] (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:163:39)
-----------

my node is v4.2.1

tern-for-vim is the latest code.

.tern-project is here:

{
    "libs": ["jquery"],
    "plugins": {
        "node": {}
    }
}

------
Any comments?

**Comment by yyangonline** [comment]
Here is the result for omni-complete:

-----

/usr/local/bin/node /Users/a/.vim/bundle/tern_for_vim/autoload/../node_modules/tern/bin/tern --verbose
Listening on port 64106

Request: {
  "files": [
    {
      "text": "/**\n * Sample React Native App\n * https://github.com/facebook/react-native\n */\n'use strict';\n\nvar React = require('react-native');\nvar {\n  AppRegistry,\n  StyleSheet,\n  Text,\n  View,\n  Navigator,\n  NavigatorIOS,\n} = React;\n\nvar TimerMixin = require('react-timer-mixin');\n\nvar SplashScreen = require('./SplashScreen');\nvar MainScreen = require('./MainScreen');\nvar StoryScreen = require('./StoryScreen');\nvar fs =require('fs');\nfs.\n\n\n\nvar _navigator;\n\nvar RCTZhiHuDaily = React.createClass({\n  mixins: [TimerMixin],\n\n  getInitialState: function() {\n    return {\n      splashed: false,\n    };\n  },\n\n  componentDidMount: function() {\n    this.setTimeout(\n      () => {\n        this.setState({splashed: true});\n      },\n      2000,\n    );\n  },\n\n  RouteMapper: function(route, navigationOperations, onComponentRef) {\n    _navigator = navigationOperations;\n    // return (\n    //   <View style={styles.container}>\n    //     <MainScreen navigator={navigationOperations}/>\n    //   </View>\n    // );\n    if (route.name === 'home') {\n      return (\n        <View style={styles.container}>\n          <MainScreen navigator={navigationOperations}/>\n        </View>\n      );\n    } else if (route.name === 'story') {\n      return (\n        <View style={styles.container}>\n          <StoryScreen\n            style={{flex: 1}}\n            navigator={navigationOperations}\n            story={route.story} />\n        </View>\n      );\n    }\n  },\n\n  render: function() {\n    if (this.state.splashed) {\n      var initialRoute = {name: 'home'};\n      return (\n        // <NavigatorIOS\n        //   style={styles.container}\n        //   initialRoute={{\n        //     title: '首页',\n        //     component: MainScreen,\n        //   }}\n        // />\n        <Navigator\n          style={styles.container}\n          initialRoute={initialRoute}\n          configureScene={() => Navigator.SceneConfigs.FadeAndroid}\n          renderScene={this.RouteMapper}\n        />\n      );\n      // return (\n      //   <View style={styles.container}>\n      //     <MainScreen />\n      //   </View>\n      // );\n    } else {\n      return (\n        <SplashScreen />\n      );\n    }\n  }\n});\n\nvar styles = StyleSheet.create({\n  container: {\n    flex: 1,\n  },\n});\n\nAppRegistry.registerComponent('RCTZhiHuDaily', () => RCTZhiHuDaily);\n",
      "type": "full",
      "name": "index.ios.js"
    }
  ],
  "query": {
    "end": {
      "line": 22,
      "ch": 3
    },
    "docs": true,
    "lineCharPositions": true,
    "file": "#0",
    "type": "completions",
    "types": true
  }
}
/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/lib/infer.js:1100
    return inferExprVisitor[node.type](node, scope, c, out, name);
                                      ^

TypeError: inferExprVisitor[node.type] is not a function
    at infer (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/lib/infer.js:1100:39)
    at Object.walk.make.Expression (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/lib/infer.js:1105:7)
    at c (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.base.ExpressionStatement (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:176:5)
    at c (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.skipThrough [as Statement] (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:163:39)
    at c (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.base.Program.base.BlockStatement (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:171:7)
    at c (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:60:37)
    at Object.skipThrough [as Statement] (/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/node_modules/acorn/util/walk.js:163:39)

**Comment by marijnh** [comment]
I could not reproduce this. You could try upgrading Acorn (the parser used by Tern) by going to `/Users/a/.vim/bundle/tern_for_vim/node_modules/tern/` and running `npm upgrade`. If it still occurs, can you give me more precise instructions for setting up the project that triggers this?

**Comment by yyangonline** [comment]
Great!! It's work for me now.Thanks!
