### ISSUE TITLE
Get the error `var defs = [], src = config.libs.slice();` with any tern interaction

### ISSUE THREAD

**Issue by dtoebe** [ternjs/tern#724]
```
/usr/lib/node_modules/tern/bin/tern:85
  var defs = [], src = config.libs.slice();
                                   ^

TypeError: config.libs.slice is not a function
    at findDefs (/usr/lib/node_modules/tern/bin/tern:85:36)
    at startServer (/usr/lib/node_modules/tern/bin/tern:169:14)
    at Object.<anonymous> (/usr/lib/node_modules/tern/bin/tern:166:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

I get this error in tern_for_vim,  Spacemacs implementation of tern and in the terminal by typing tern (which I used npm to install globally)

I get this no matter what flag I try to apply in the CLI.  I am using tern@0.17.0

**Comment by marijnh** [comment]
Could it be that you have a project config file that sets `libs` to something that's not an array?

**Comment by dtoebe** [comment]
(face palm) that was it thanks
