### ISSUE TITLE
Error: Invalid !type spec: SpeechRecognitionStatic

### ISSUE THREAD

**Issue by ackalker** [ternjs/tern#731]
To create a type definition file for the Web Speech API, I used the command:
```sh
from_ts "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/webspeechapi/webspeechapi.d.ts" > webspeechapi.json
```

When I try and use `webspeechapi.json` with Tern, I get the following error:
```
/home/miki/.local/lib/node_modules/tern/lib/def.js:392
        else throw new Error("Invalid !type spec: " + tp);
             ^

Error: Invalid !type spec: SpeechRecognitionStatic
    at passOne (/home/miki/.local/lib/node_modules/tern/lib/def.js:392:20)
    at passOne (/home/miki/.local/lib/node_modules/tern/lib/def.js:405:7)
    at doLoadEnvironment (/home/miki/.local/lib/node_modules/tern/lib/def.js:461:5)
    at Object.exports.load (/home/miki/.local/lib/node_modules/tern/lib/def.js:487:7)
    at /home/miki/.local/lib/node_modules/tern/lib/infer.js:858:13
    at Object.exports.withContext (/home/miki/.local/lib/node_modules/tern/lib/infer.js:872:18)
    at new exports.Context (/home/miki/.local/lib/node_modules/tern/lib/infer.js:840:13)
    at Object.signal.mixin.reset (/home/miki/.local/lib/node_modules/tern/lib/tern.js:146:17)
    at Object.exports.Server (/home/miki/.local/lib/node_modules/tern/lib/tern.js:126:10)
    at startServer (/home/miki/.local/lib/node_modules/tern/bin/tern:171:16)
```

I don't understand Tern type definitions or the conversion from TypeScript definitions well enough to know if this is a bug or if I need to do any manual touch-ups on the `.d.ts` file before it can be converted and used with Tern. Please advise.

**Comment by marijnh** [comment]
`from_ts` was removed (it was targeting a very old TypeScript syntax and not being maintained), and since this seems to point at a bug in that tool, I'm going to close it.
