### ISSUE TITLE
from_ts does not complete for electron

### ISSUE THREAD

**Issue by mrennie** [ternjs/tern#761]
Recently I tried running `from_ts` on the following url:

> https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/github-electron/github-electron.d.ts

It ran for a little bit and then barfed out the following exception:

> Error: Unknown field type: ExpressionStatement
    at objType (/Users/mrennie/git/tern/lib/typescript.js:147:13)
    at Object.exports.translate (/Users/mrennie/git/tern/lib/typescript.js:212:14)
    at finish (/Users/mrennie/git/tern/bin/from_ts:28:33)
    at IncomingMessage.<anonymous> (/Users/mrennie/git/tern/bin/from_ts:17:7)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

The complete command line I used is:

> ./from_ts https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/github-electron/github-electron.d.ts --no-spans --plugin node --def ecma5 --def ecma6 --name electron  >  electron.json

**Comment by marijnh** [comment]
`from_ts` isn't in the repository anymore, and hadn't been maintained for a while even before it was removed.
