### ISSUE TITLE
Can't find definition even when tern can find signature

### ISSUE THREAD

**Issue by Wilfred** [ternjs/tern#822]
Given the following code:

```js
var _ = require('lodash');

function foo() {
  var x = {a: 1, b:2, c: 2};
  return _.mapValues(x, function(v) { return v + 1;});
}
```

Tern has no problems finding the signature of `_.mapValues`:

```
Request: {
  "files": [
    {
      "type": "full",
      "text": "var _ = require('lodash');\n\nfunction foo() {\n  var x = {a: 1, b:2, c: 2};\n  return _.mapValues(x, function(v) { return v + 1;});\n}\n",
      "name": "foo.js"
    }
  ],
  "query": {
    "end": 94,
    "file": "foo.js",
    "type": "type",
    "preferFunction": true
  }
}
Response: {
  "guess": true,
  "type": "fn(object: x, iteratee?: ?) -> result",
  "name": "mapValues",
  "exprName": "mapValues",
  "doc": "Creates an object with the same keys as `object` and values generated by running each own enumerable string keyed property of `object` thru `iteratee`.",
  "origin": "node_modules/lodash/lodash.js"
}
```

However, when I try to jump to the current definition, tern doesn't find anything:

```
Request: {
  "query": {
    "end": 90,
    "file": "foo.js",
    "type": "definition",
    "variable": null
  }
}
Response: {}
```

I'm using tern 0.20.0 and my .tern-project is:

```json
{
    "plugins": {
        "node": {}
    }
}
```

Is this expected? I'm surprised that tern can find the signature, so it's clearly found the lodash code, but won't jump to definition.

**Comment by Wilfred** [comment]
I tried explicitly setting the variable name (with `M-x tern-find-definition-by-name`) but that just errors out:

```json
Request: {
  "query": {
    "end": 85,
    "file": "foo.js",
    "type": "definition",
    "variable": "mapValues"
  }
}
TypeError: Cannot read property 'ast' of undefined
    at Array.isImport (/users/is/whughes/tmp/demojs/node_modules/tern/plugin/commonjs.js:52:58)
    at Object.signal.mixin.findIn (/users/is/whughes/tmp/demojs/node_modules/tern/plugin/modules.js:75:28)
    at Object.signal.mixin.isImport (/users/is/whughes/tmp/demojs/node_modules/tern/plugin/modules.js:81:49)
    at Object.signal.mixin.getModType (/users/is/whughes/tmp/demojs/node_modules/tern/plugin/modules.js:128:42)
    at Array.findTypeAt (/users/is/whughes/tmp/demojs/node_modules/tern/plugin/modules.js:243:22)
    at findExprType (/users/is/whughes/tmp/demojs/node_modules/tern/lib/tern.js:860:31)
    at Object.findDef [as run] (/users/is/whughes/tmp/demojs/node_modules/tern/lib/tern.js:971:16)
    at run (/users/is/whughes/tmp/demojs/node_modules/tern/lib/tern.js:268:59)
    at /users/is/whughes/tmp/demojs/node_modules/tern/lib/tern.js:271:16
    at Object.exports.withContext (/users/is/whughes/tmp/demojs/node_modules/tern/lib/infer.js:869:18)
Response: 400 TypeError: Cannot read property 'ast' of undefined
```
