### ISSUE TITLE
Webpack plugin doesn't resolve in other roots

### ISSUE THREAD

**Issue by LubergAlexander** [ternjs/tern#883]
Minimal repo to reproduce: https://github.com/LubergAlexander/ternjs-webpack-resolver-bug

`npm i && npm run build` builds the bundle successfully using the webpack config in the repo.

`tern --verbose` shows an exception when trying to resolve the module using webpack:

```
Error: Can't resolve 'utils/testUtil' in '/Users/aluberg/Code/tern_webpack_resolve'
    at onResolved (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/Resolver.js:66:16)
    at loggingCallbackWrapper (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/usr/local/lib/node_modules/tern/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /usr/local/lib/node_modules/tern/node_modules/tapable/lib/Tapable.js:283:15
    at /usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
Error: Can't resolve 'utils/sampleModule' in '/Users/aluberg/Code/tern_webpack_resolve'
    at onResolved (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/Resolver.js:66:16)
    at loggingCallbackWrapper (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
    at loggingCallbackWrapper (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/usr/local/lib/node_modules/tern/node_modules/tapable/lib/Tapable.js:181:46)
    at innerCallback (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
    at loggingCallbackWrapper (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at /usr/local/lib/node_modules/tern/node_modules/tapable/lib/Tapable.js:283:15
    at /usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:39:4
    at loggingCallbackWrapper (/usr/local/lib/node_modules/tern/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
```

Webpack allows specifying multiple paths to resolve from using resolve.root.

```javascript
  resolve: {
    root: [
      "node_modules",
      path.resolve(__dirname, "src/js")
    ]
  },
```

**Comment by LubergAlexander** [comment]
@chemzqm 
same happens for both webpack 1 & 2

**Comment by chemzqm** [comment]
Didn't know the root could be an array, I will fix this.

**Comment by LubergAlexander** [comment]
👍 Thanks!
