### ISSUE TITLE
Rest syntax causing failure on version 0.22.1

### ISSUE THREAD

**Issue by FuzzOli87** [ternjs/tern#984]
This might be related to: https://github.com/ternjs/tern/issues/982

```javascript
const obt = {
  hi: 'hello'
};

const {
  hi,
  ...obj
} = obj;
```

Causes a failure with the following error and request:
```
Request: {
  "query": {
    "type": "completions",
    "types": false,
    "depths": false,
    "docs": false,
    "filter": true,
    "caseInsensitive": false,
    "guess": true,
    "sort": false,
    "expandWordForward": true,
    "omitObjectPrototype": false,
    "includeKeywords": false,
    "inLiteral": true,
    "file": "#0",
    "end": {
      "line": 7,
      "ch": 4
    },
    "lineCharPositions": true
  },
  "files": [
    {
      "type": "full",
      "name": "tern.js",
      "text": "const obt = {\n  hi: 'hello'\n};\n\nconst {\n  hi,\n  ...obj\n} = he"
    }
  ]
}
/home/fuzz/.npm-global/lib/node_modules/tern/lib/infer.js:1189
    if (!node.computed && key.type == "Identifier") return key.name;
                              ^

TypeError: Cannot read property 'type' of undefined
    at exports.propName (/home/fuzz/.npm-global/lib/node_modules/tern/lib/infer.js:1189:31)
    at ObjectPattern (/home/fuzz/.npm-global/lib/node_modules/tern/lib/infer.js:1270:58)
    at connectPattern (/home/fuzz/.npm-global/lib/node_modules/tern/lib/infer.js:1285:20)
    at Object.VariableDeclaration (/home/fuzz/.npm-global/lib/node_modules/tern/lib/infer.js:1682:11)
    at c (/home/fuzz/.npm-global/lib/node_modules/tern/node_modules/acorn/dist/walk.js:57:35)
    at Object.Statement (/home/fuzz/.npm-global/lib/node_modules/tern/lib/infer.js:1671:7)
    at c (/home/fuzz/.npm-global/lib/node_modules/tern/node_modules/acorn/dist/walk.js:57:35)
    at Object.base.Program.base.BlockStatement (/home/fuzz/.npm-global/lib/node_modules/tern/node_modules/acorn/dist/walk.js:195:5)
    at c (/home/fuzz/.npm-global/lib/node_modules/tern/node_modules/acorn/dist/walk.js:57:35)
    at Object.recursive (/home/fuzz/.npm-global/lib/node_modules/tern/node_modules/acorn/dist/walk.js:58:5)
```

**Comment by othree** [comment]
Yes, the same issue, but caused by RestElement.
Fixing, thank you report the issue.
